### ISSUE TITLE
Custom-ui templated attributes dont show in dev tools and backend Jinja templates

### ISSUE THREAD

**Issue by SiriosDev** [Mariusthvdb/custom-ui#110] opened 2023-11-17 22:29 UTC
After adding `icon_color` via `customization` it doesn't appear in attributes, i.e. unusable with templates, the most I got is `icon_color` under `templates` but it's just the js code

below are respectively:
- list of attributes
- screenshot of the webui 
- piece of `customization`

<table> <tr> <td>

```jinja2
//
//
{% set SENSOR = 'sensor.pirateweather_apparent_temperature' %}
{% for attr in states [SENSOR].attributes %}
{{ attr }} 
{% endfor %}
//
//
```
</td> <td>

```yaml
state_class 

attribution 

unit_of_measurement 

device_class 

friendly_name 

hide_attributes 

templates
```
</td> </tr> </table>

![image](https://github.com/Mariusthvdb/custom-ui/assets/26876994/1bcf4946-d370-44f4-a0b8-613ce24b4cca)

```yaml
#customizaion.yaml
sensor.pirateweather_apparent_temperature:
  templates:
    icon_color: >
      const val = parseInt(state);
      const valColorMap = [
        { value: -10, color: "#0033ff" },
        { value: -8, color: "#0963ff" },
#removed some entry for better reading
        { value: 24, color: "#feac07" },
        { value: 26, color: "#fb9300" },
        { value: 28, color: "#ff6f00" },
        { value: 30, color: "#ff4802" },
        { value: 32, color: "#ff2803" },
        { value: 34, color: "#ff0506" },
        { value: 36, color: "#d9031e" },
        { value: 38, color: "#b90135" },
        { value: 40, color: "#930058" },
        { value: 42, color: "#70016f" }
      ];

      var color;
      for (const vcm of valColorMap) {
        if (val < vcm.value) {
          color = vcm.color;
          break;
        }
      }

      return color;

```

**Comment by Mariusthvdb** [comment] 2023-11-18 09:26
first things first: did you install custom-ui? (show inspector console to be sure)

if yes, please add a simple customization like
```
homeassistant:
  customize:
    sensor.pirateweather_apparent_temperature:
      icon_color: red
```

to see if its working as it should

**Comment by SiriosDev** [comment] 2023-11-18 10:39
> first things first: did you install custom-ui? (show inspector console to be sure)

I'm not sure, but I think you mean this?
![image](https://github.com/Mariusthvdb/custom-ui/assets/26876994/d65634c1-e408-4169-b2ad-714abbdf1aa9)

> next:where did you ad this customization? it should be in the correct hierarchy compared to homeassisant, see the docs.


above (_hierarchically_) I only have this glob (to make the webui neat ) :
```yaml
"*.*":
  hide_attributes:
    - templates
```

now know that I wrote the code, following [this page](https://github.com/Mariusthvdb/custom-ui/blob/master/EXAMPLES.md#formats) (specifically I read the piece from `sensor.synology_status_volume_1`) that says to put `icon_color` inside `templates`

anyway, 
# this working
> ```
> homeassistant:
>   customize:
>     sensor.pirateweather_apparent_temperature:
>       icon_color: red
> ```


# this not working
> ```
>           icon_color: >
>             if (state === 'unknown') return 'grey';
>             if (state < -20) return 'black';
>             if (state < -15) return 'navy';
>             if (state < -10) return 'darkblue';
>             if (state < -5) return 'mediumblue';
>             if (state < 0) return 'blue';
>             if (state < 5) return 'dodgerblue';
>             if (state < 10) return 'lightblue';
>             if (state < 15) return 'turquoise';
>             if (state < 20) return 'lightgreen';
>             if (state < 25) return 'darkgreen';
>             if (state < 30) return 'orange';
>             if (state < 35) return 'crimson';
>             return 'firebrick';
> ```

unfortunately as before it has effect on the web ui, but I can't get it via jinja template (on the contrary the one before to put it red works)

> simplify that mapper, not sure where you got that from.... I didnt yet meet a beginner on custom-ui with a syntax as complex as that.

I didn't find it 😅😅, I wrote it based on an old jinja2 template I used before

**Comment by SiriosDev** [comment] 2023-11-18 10:40
i saw the edits now i will try those as well

**Comment by Mariusthvdb** [comment] 2023-11-18 11:31
Not sure what you mean getting it via Jinja templates?

**Comment by SiriosDev** [comment] 2023-11-18 12:12
as you wrote in the readme, some cards are incompatible, we need to use card-mod, which uses jinja templates (also called home assistant templates) to set the color of these incompatible cards

## customization entry

```yaml

sensor.pirateweather_apparent_temperature: 
  templates:
    icon_color: >
      const val = parseInt(state);
      const valColorMap = [
        { value: -20, color: 'black' },
        { value: -15, color: 'navy' },
        { value: -10, color: 'darkblue' },
        { value: -5, color: 'mediumblue' },
        { value: 0, color: 'blue' },
        { value: 5, color: 'dodgerblue' },
        { value: 10, color: 'lightblue' },
        { value: 15, color: 'turquoise' },
        { value: 20, color: 'lightgreen' },
        { value: 25, color: 'darkgreen' },
        { value: 30, color: "orange" },
        { value: 35, color: "crimson" }
      ];

      return valColorMap.find(mapping => val < mapping.value)?.color || 'firebrick';
```

## card config

```yaml
type: tile
entity: sensor.pirateweather_apparent_temperature
vertical: false
name: Percepita
show_entity_picture: false
card_mod:
  style: |
    ha-card {
        --tile-color: {{state_attr ('sensor.pirateweather_apparent_temperature', 'icon_color')}} !important;
    }

```
![image](https://github.com/Mariusthvdb/custom-ui/assets/26876994/2d8197f1-7a3e-4395-b735-39cddae0ec42)
![image](https://github.com/Mariusthvdb/custom-ui/assets/26876994/affdfb43-caec-4169-938a-14d6581ff209)


# working example (but with template sensor)

## sensor entry
```yaml
- sensor:
    - name: "uv_level"
      unique_id: 439bafe4-af31-4683-b249-b7ed53e6ee5b
      icon: mdi:sun-wireless
      state: >-
        {% from 'uv_tool.jinja' import uv_index2level %}
        {{ uv_index2level('sensor.pirateweather_uv_index', 'binary_sensor.notte') }}
      attributes:
        icon_color: >-
          {%- set state = this.state %}
          {%- if state == "Basso" %}
          #008000
          {%- elif state == "Medio" %}
          #ffff00
          {%- elif state == "Alto" %}
          #ffa500
          {%- elif state == "Molto Alto" %}
          #ff0000
          {%- elif state == "Estremo" %}
          #8a2be2
          {%- endif %}
```

## card configuration
```yaml
type: tile
vertical: false
entity: sensor.uv_level
card_mod:
  style: |
    ha-card {
        --tile-color: {{state_attr ('sensor.uv_level', 'icon_color')}} !important;
    }
```
![image](https://github.com/Mariusthvdb/custom-ui/assets/26876994/b20afd7c-5f82-4b07-a5fc-18f84b898e44)
![image](https://github.com/Mariusthvdb/custom-ui/assets/26876994/239c2feb-ac80-4f4e-904e-02b4be2327ba)

**Comment by Mariusthvdb** [comment] 2023-11-18 13:26
sorry, but you are not going to solve your JS card with showing jinja templates....

please keep the issue tidy, because this is rather confusing.

your top post is a regular more-info of a singel entity, so that should just work with the templates I provided.

please keep your search to solving that in your config.

did you give it a restart in between changing those templates? Normally, the change would kick in on a reload of customizations, and a state change. Sometimes, a restart is needed.

all I can think of is that your customization is not placed correctly in your yaml, thats why I asked to show the full yaml structure

**Comment by SiriosDev** [comment] 2023-11-18 13:40
you're right let's go step by step

- your extension allows you to add fields dynamically in customize via js, for example `icon_color`, right?
- as written in the readme not all cards are directly compatible with this `icon_color` (to solve it you recommend using `card-mod`), so it becomes necessary to somehow "extract" this field to use it (in `card-mod`), and the only way to do that is to use HA templates (`jinja`)
- as written in the first comment of this issue, this `icon_color` field is not in the list of attributes which makes it impossible to use it, appears only in the webui
  - after when you asked me to try the red only version that you showed me it worked, both via template and webui

**Comment by Mariusthvdb** [comment] 2023-11-18 13:52
well, your last statement is not correct. As a matter of fact, you can use the icon_color attribute in any other template or config, as it's added to the entity directly.

That has nothing to do with the cards in the Frontend.

some Frontend cards see the attribute icon_color, and some dont. If not, then you need to find another way to do what you want (can be card_mod, or other custom card)

concluding:

as is displayed by your colored icons in all screenshots above, custom-ui is working properly.
seems we can close, and you need to take your quest to the community is you still have one.

**Comment by SiriosDev** [comment] 2023-11-18 14:13
there is absolutely no question that the color is computed correctly, as you say the icon changes color in the `more-info` popup, the problem is that the HA templates and consequently `card-mod` do not see this "field".

the following template string `{{state_attr ('sensor.pirateweather_apparent_temperature', 'icon_color')}}`, _is (almost) the user friendly version of the command I put in the first comment_, it returns an attribute value given an `entity` and the `attribute name`, the problem is that it returns nothing.

**Comment by Mariusthvdb** [comment] 2023-11-18 20:04
Please post a screenshot of this entity in dev tools /states?

**Comment by SiriosDev** [comment] 2023-11-18 20:23
here
![image](https://github.com/Mariusthvdb/custom-ui/assets/26876994/d95be38f-a60e-4e77-9b4d-244aa789404a)

**Comment by Mariusthvdb** [comment] 2023-11-18 22:06
yes, I now see what you mean, and., tbh, that is new to me. reading back, I now also understand your post.....

great find.

In all the years I use custom-ui, this never happened.

either something changed in the attributes handling in core HA, or the latest update(s) of custom-ui broke that functionality..

maybe I need to reiterate and subsequently test the last few version.....

I dont think the hide attributes has anything to do with it, but it is the simplest test we can do, by leaving that out and see what happens.

**Comment by SiriosDev** [comment] 2023-11-18 22:14
Oh, great finally! Sorry if I've misspoke so far. 😅😅

I can tell you right now that even without `hide` it doesn't work, my first attempt was without hide, in fact during my try and error I thought `hide` was a requirement for it to work

**Comment by Mariusthvdb** [comment] 2023-11-18 22:17
yes, Ive asked in dev core on discord, and meanwhile I see it happening system wide. All works, except the attribute in the template., or the attributes column...

let me try a fixed color

**Comment by SiriosDev** [comment] 2023-11-18 22:23
yea i confirm setting a fixed color, without template like the first snippet [here](https://github.com/Mariusthvdb/custom-ui/issues/110#issuecomment-1817455639), work perfectly

**Comment by Mariusthvdb** [comment] 2023-11-18 22:36
well, ive gone back to my original custom-ui as far back as possible, and none of them show the templated attributes anymore.
So definitely a change I HA handling of those...
yet another set back for custom-ui users, though not completely disastrous, as this is an edge case usecase...

it might also be a bug, so Ill file it anyways, if only because of the discrepancy between the attributes filter listing and the set state box...

**Comment by SiriosDev** [comment] 2023-11-18 22:41
yeah sure, imho may be a bug, cause work everywhere except templates

**Comment by Mariusthvdb** [comment] 2023-11-20 07:16
as a side note:
the 'experimental' functionality to set an attribute `icon_color` on a template sensor in HA yaml directly does make the attribute appear and allow it to be templated

<img width="903" alt="Scherm­afbeelding 2023-11-20 om 08 12 55" src="https://github.com/Mariusthvdb/custom-ui/assets/33354141/ea8d75b6-f2a7-4fa6-b7f1-c6ae71a50793">

<img width="840" alt="Scherm­afbeelding 2023-11-20 om 08 13 28" src="https://github.com/Mariusthvdb/custom-ui/assets/33354141/5ac8ce67-1e26-427b-b007-57fce3717ea7">

```
        attributes:
#experimental!
          icon_color: >
            {{'gold' if this.state|int(default=-1) != 0 else 'gray'}}
```

ofc, this can only be done on entities of integrations that support custom attributes in HA core by design, like the template integration.

also note it does not show the template itself in the attributes, which ofc is nice, as it doesnt fill the state machine with that code.

Not fixing the issue at hand, just letting you know

**Comment by SiriosDev** [comment] 2023-11-20 10:31
Yeye I know already using it on temples entities

**Comment by Mariusthvdb** [comment] 2023-11-22 10:46
hmm, I now see the icon_color attribute itself is also missing. How strange, as the above screens show it's still there.
maybe a cache thing.
I did check the template integration in HA, but dont see an obvious change there yet.
maybe we need to downgrade and see if 2023.10 brings it back

**Comment by SiriosDev** [comment] 2023-11-22 21:36
thats strange

**Comment by SiriosDev** [comment] 2023-11-28 23:19
at the moment I am not very familiar with HA integrations, but never say never, if I figure out how to do it I will definitely make a pr

**Comment by SiriosDev** [comment] 2023-12-12 23:48
Soo. At the moment, I solved it with the following workaround, which is to use the python script [Entities Script](https://github.com/pmazz/ps_hassio_entities) (from HACS) and an automation that runs on each state change by setting the custom attribute one of the services offered

**Comment by SiriosDev** [comment] 2023-12-12 23:53
here the yaml for who need it (based on the entity at the top of this issue)
```yaml

alias: Temp Colorizer
description: "Set Entity color based on state"
trigger:
  - platform: state
    entity_id:
      - sensor.pirateweather_apparent_temperature
condition: []
action:
  - service: python_script.hass_entities
    data:
      action: set_attributes
      entity_id: sensor.pirateweather_apparent_temperature
      attributes:
        - icon_color: |
            {% from 'temperature_colorzier.jinja' import outside_temp %}
            {{ outside_temp('sensor.pirateweather_apparent_temperature') }}
mode: queued
max: 10
```

the custom jinja code chose a color from an array of tuple (temp - color)

**Comment by Mariusthvdb** [comment] 2023-12-13 08:51
there's a lot to be said about that workaround, but most of all, it would become terribly cumbersome doing so for many entities, and it would trigger the state machine constantly.....

you (we) are probably better off trying to find ways not requiring that attribute at all. I mean, where do you need it?

Personally, I've taken out all icon_color attributes except on the template entities (remember: this is an experimental feature made possible by custom-ui) where they are actually visible I the attributes list and iterable,

Other than that, I use card-mod for spicing up the Frontend, and stopped using custom-ui template completely.

(Only downside of that is that the more-info's no longer get the icon_color...)

**Comment by bratanon** [comment] 2024-01-03 23:38
Explaining this process involves a technical discussion, but I'll attempt to clarify the concepts:

The custom-ui functionality involves the interception of the `homeassistant` JavaScript class. This interception targets a specific custom element named `homeassistant`, where templates specified in YAML attributes are computed. These computed templates are then utilized to modify state objects through the custom element called `state-badge`, thereby effecting changes in the frontend system.

The widespread presence of the `homeassistant` custom element allows custom-ui to potentially alter state objects across various pages in the system.

However, there is a limitation when it comes to the "_dev tools template_" section, as it does not utilize the `state-badge` custom element. Consequently, modifications made by custom-ui are not applicable in this section, and the state object is read as originally defined in YAML.

This constraint is inherent, and there's no feasible solution.

The computed templates, visible in the "_dev tools state_" section, are a product of custom-ui's template computation.

Regarding card mod, it calculates Jinja templates by invoking a backend service. However, since the backend is unaware of custom-ui's actions, the results only include attributes defined in YAML. Essentially, using custom-ui in conjunction with card mod in this manner is not viable.

**Comment by bratanon** [comment] 2024-01-03 23:41
@SiriosDev @Mariusthvdb I think we can close this as "wont fix", what is your thoughts?

**Comment by Mariusthvdb** [comment] 2024-01-04 09:01
Agreed

cant help but remember we could see the templates outcome in Jinja before but can’t reproduce in any older version.

lets go forward.

**Closed** 2024-01-04 20:21 UTC
