### ISSUE TITLE
Customization is being ignored within paper-buttons-row

### ISSUE THREAD

**Issue by drew-kun** [Mariusthvdb/custom-ui#5] opened 2020-06-14 20:09 UTC
### Checklist
- [x] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [x] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** 
Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**CustomUI version:** 
CustomUI: 20200520-adapted-for-HA110+

**Home Assistant release (`hass --version`):** 
0.110.2

**Problem-relevant `configuration.yaml` entries:**
```yaml
frontend:
  extra_module_url:
  - /local/custom_ui/state-card-custom-ui.js

homeassistant:
  customize_domain:
    climate:
      templates:
        icon_color: >
          if (state == 'heat_cool') return '#99AC18';
          if (state == 'heat') return '#F58019';
          if (state == 'cool') return '#268AD2';
          if (state == 'dry') return '#FFC100';
        icon: >
          if (state == 'heat_cool') return 'mdi:sync';
          if (state == 'heat') return 'mdi:fire';
          if (state == 'cool') return 'mdi:snowflake';
          if (state == 'dry') return 'mdi:water-percent';
          if (state == 'fan_only') return 'mdi:fan';
          return 'mdi:air-conditioner';

  customize:
    switch.all_climate_heat_cool:
      templates:
        icon_color: if (state == 'on') return '#99AC18';  # 'rgb(154, 171, 33)';  # Solarized Green
    switch.all_climate_heat:
      templates:
        icon_color: if (state == 'on') return '#F58019';  # 'rgb(245, 128, 25)';  # Orange
    switch.all_climate_cool:
      templates:
        icon_color: if (state == 'on') return '#268AD2';  # 'rgb(76, 154, 218)';  # Solarized Blue
    switch.all_climate_dry:
      templates:
        icon_color: if (state == 'on') return '#FFC100';  # 'rgb(248, 192, 30)';  # Solarized Yellow
```

**ui-lovelace.yaml** - comparison: entities card vs paper-buttons-row (within auto-entities card)
```yaml
...
  - type: entities
    title: Climate
    entities:
    - climate.kitchen_ac
    - climate.bedroom_ac
    footer:
      type: buttons
      entities:
      - switch.all_climate_heat_cool
      - switch.all_climate_heat
      - switch.all_climate_cool
      - switch.all_climate_dry
      - switch.all_climate_power_off

  - type: custom:auto-entities
    card:
      type: entities
      title: Climate
      show_header_toggle: false
    entities:
    - climate.kitchen_ac
    - climate.bedroom_ac
    - type: custom:paper-buttons-row
      buttons:
      - entity: switch.all_climate_heat_cool
        name: false
      - entity: switch.all_climate_heat
        name: false
      - entity: switch.all_climate_cool
        name: false
      - entity: switch.all_climate_dry
        name: false
      - entity: switch.all_climate_power_off
        name: false
...
```

**Result:** 
- Entities card (the above) colorizes switches in accordance with the customization (snowflake is blue).
- Auto-entities (the below) colorizes climate entities in accordance with the customization (snowflake is blue).
- paper-buttons-row (the below row) seems to ignore the customization (snowflake is yellow).

![Screen Shot 2020-06-14 at 1 26 39 PM](https://user-images.githubusercontent.com/10493450/84591022-d81c5a00-ae43-11ea-8d4a-e45700c13db6.png)

**Problem-relevant Home Assistant log entries:**
```

```

**Any errors from browser Javascript console:**
```

```

**Comment by drew-kun** [comment] 2020-06-14 20:09
https://github.com/andrey-git/home-assistant-custom-ui/issues/190

**Comment by Mariusthvdb** [comment] 2020-06-14 21:10
thanks for the issue. Ive been able to confirm the custom card paper-buttons-row doesn't use the customized `icon_color:`

not much we can do here for now, but will let you know if and when news on the issue is to be expected.
Could very well be an issue with that custom card, so please do alert the author too.

**Comment by jcwillox** [comment] 2020-06-15 07:35
Hey, so is `icon_color` meant to be a part core Home Assistant, as in handled by the native components, or would `paper-buttons-row` need to extract this itself from the entities attributes?

Regardless of if this is being set as the default colour for each `paper-button` it will be overridden by the plugin as it uses its own mechanism for styling based on state, however, it doesn't override the CSS var `--paper-icon-active-color`.

**Comment by Mariusthvdb** [comment] 2020-06-15 07:48
thanks for chiming in!
not really sure tbh. Custom-ui adds the attribute icon_color, which wasn't in core at the time of its development, and still isn't, afaik.

Up to now, all appearances of a customized entity using custom-ui's icon_color seem to use that, globally in HA. 

maybe this can help: https://github.com/home-assistant/frontend/issues/5892#issuecomment-630872617 as it explains what custom-ui sets to have it work in core HA.

**Comment by jcwillox** [comment] 2020-06-15 09:30
Thanks, I checked out that issue and it makes sense what's happening.
Paper-buttons-row doesn't use the `state-badge` element is uses a plain `ha-icon` which from what I can tell isn't touched by `custom-ui`.

So, the options are either switch to using a state-badge or to implement styling based on the `icon_color` attribute. Which naturally I'll handle over at [paper-buttons-row](https://github.com/jcwillox/lovelace-paper-buttons-row).

The only thing I'm not clear on is the standard implementation of `icon_color` meant to override both the default and active colors?

**Comment by Mariusthvdb** [comment] 2020-06-15 10:10
Afraid there is no such thing as a standard implementation of `icon_color` unfortunately.

Maybe we'd be best to ask the core frontend developers this. No use changing now, while core is heading another direction.
Ive fixed custom-ui for 110.+, but am I now way assured this will stay...
I do know the author of Custom Header is having a look, and of course Bram.

If you could support icon_color as set by custom-ui, that would be really appreciated though ;-)

**Comment by Mariusthvdb** [comment] 2020-09-26 20:07
guess we can close this, since it is more a thing with paper-buttons-row, than custom-ui.

**Closed by Mariusthvdb** 2020-09-26 20:07 UTC
