### ISSUE TITLE
Icon color not working in 2023.1

### ISSUE THREAD

**Issue by kristianolofsson** [Mariusthvdb/custom-ui#86] opened 2023-01-09 20:05 UTC
Used my prev config from Ver 2022.x and works fine. Upgraded to 2023.1 and no icons are no longer colored.
Attribut logic still works but not working.

**Comment by Mariusthvdb** [comment] 2023-01-09 23:45
Please add some context...

Config, yaml, templates and screenshot of a failing entity in dev tools

**Comment by ildar170975** [comment] 2023-01-10 13:34
Latest version:
![image](https://user-images.githubusercontent.com/71872483/211564979-f2d9ab48-2051-4ce2-9fa0-7b146d9e6503.png)

Customization:
```
homeassistant:
  customize_glob:

    input_number.test_level_3:
      templates:
        icon_color: >-
          return 'magenta';

    input_number.test_level_4:
      templates:
        friendly_name: >-
          return 'custom_name';
```
Card:
```
  - type: entities
    entities:
      - entity: input_number.test_level_3
      - entity: input_number.test_level_4
```
![image](https://user-images.githubusercontent.com/71872483/211564697-eac1d68f-9f5a-4a8a-8659-2707d28a79a9.png)

Dev tools:
![image](https://user-images.githubusercontent.com/71872483/211564752-38f17637-d7d2-429a-9af6-d0fc2a38456c.png)
![image](https://user-images.githubusercontent.com/71872483/211564771-f533eb41-7357-4252-bee7-03a1668cd796.png)

**Comment by ildar170975** [comment] 2023-01-10 14:02
> but certainly no globs, so they should at least be listed under
> `customize:` and Not under `customize_glob:`

This code was **simplified** to:
```
homeassistant:
  customize_glob:

    input_number.test_level_3:
      templates:
        icon_color: >-
          return 'magenta';
```
from smth more complex:
```
homeassistant:
  customize_glob:
    input_number.test_level_2:      ###TODO_CUSTOM_UI
      templates:
        icon_color: >-
          if (state <= 10) return 'yellow';
          else
          if (state <= 20) return 'brown';
          else
          if (state <= 30) return 'magenta';
          else
          if (state <= 40) return 'lightblue';
          else
          if (state <= 50) return 'green';
          else
          if (state <= 60) return 'orange';
          else
          if (state <= 70) return 'purple';
          else
          if (state <= 80) return 'red';
          else
          if (state <= 90) return 'gold';
          else
          return 'cyan';
```
which does not work too.


> the friendly name is totally out of perspective, as it does not contain any template, and can be set directly in HA without custom-ui....

Same is about `friendly_name`, it is this:
```
homeassistant:
  customize_glob:
    sensor.testing_device_class_*:
      templates:
        friendly_name: >-
          if (entity)
          {
            var HEADER = 'testing_device_class_';
            var NAME = entity.entity_id.split('.')[1].split(HEADER)[1].replaceAll("_"," ");
            return NAME;
          }
          else return null;
```

**Comment by Mariusthvdb** [comment] 2023-01-10 14:06
well, the first still is no glob, so move that to customize: and please report what happens.

as for the second, why make testing so difficult. currently its hard to see if its a javascript issue, or a custom-ui issue.

> Strange, cannot find Custom UI in Code Inspector.

that would be the root cause I suspect. always check that first. without it, it just indicates the resource isnt loaded at all

**Comment by ildar170975** [comment] 2023-01-10 14:10
> as for the second, why make testing so difficult

What do you mean?
Do you mean this this code is wrong?
```
homeassistant:
  customize_glob:
    sensor.testing_device_class_xxxxxx:
      templates:
        friendly_name: >-
          return ...;
```
and it MUST BE
```
homeassistant:
  customize:
```
?

**Comment by Mariusthvdb** [comment] 2023-01-10 14:16
no, please read carefully. I wrote the first (input_number.test_level_2:) needs to be under `customize:` because it is not a glob.

the second is just a test template, but so complex you are not sure whether it is your javascript code, or the custom-ui.

but for you I just tested this

```
homeassistant:

  customize_glob:
    '*.test*':
      templates:
        templated_attribute: >
          return entity.entity_id.split('.')[1] + ' templated';


        friendly_name: >
          var splitfname = entity.entity_id.split('test')[1];
          var fname = 'Friendly name changed to: ' + splitfname;
          return fname;
```

and it works perfectly on all entities:

<img width="1208" alt="Scherm­afbeelding 2023-01-10 om 15 12 31" src="https://user-images.githubusercontent.com/33354141/211574572-988fae65-0817-4392-93ff-50558ea27bbf.png">

so, on this side, there is not a single issue on the templates or customizations. 
Since you can not see the resource in the inspector panel, that would be the main cause, and you need to fix that first

**Comment by Mariusthvdb** [comment] 2023-01-10 14:21
please confirm the correct loading of the resource (check inspector) so we can close this.

**Comment by ildar170975** [comment] 2023-01-10 14:23
> needs to be under `customize:` because it is not a glob.

This is exactly what I asked you [here](https://github.com/Mariusthvdb/custom-ui/issues/86#issuecomment-1377341331).
I believed that both ways - "apply to sensor.test_*" or "apply to sensor.test_xxxx" - should return SAME result.




> the second is just a test template, but so complex you are not sure whether it is your javascript code, or the custom-ui.

The JS code is absolutely correct.
But anyway I first replaced it with simple "return 'xxxx'" to be sure.





> please confirm the correct loading of the resource (check inspector)

Cannot confirm, not loaded according to Code Inspector after redownloading Custom UI by HACS and rebooting HA.

**Comment by Mariusthvdb** [comment] 2023-01-10 14:30
you may believe what you want of course, but as a user of custom-ui since its inception, (and a maintainer of this resource since the archival of the original custom-ui) it has been common practice to add glob customizations to the customize_glob: section, and entity customizations to customize:

I won't comment on that any further.

> 
The JS code is absolutely correct.

sure, I take your word for it, but it doesnt matter, because:

> 
not loaded according to Code Inspector 

there's not much I can say or do there other than show what I have (using yaml mode):

```
# https://github.com/Mariusthvdb/custom-ui
- url: /local/resources/custom-ui/custom-ui-gpt.js?v=20230102-entity_id
# - url: /hacsfiles/custom-ui/custom-ui.js
  type: module
```

as you can see I simply flip between those 2 when testing and reloading. no restarts required at all, let alone reboot. A mere reload resources suffices, never fails

**Comment by Mariusthvdb** [comment] 2023-01-10 14:40
not sure.
did HACS update/change anything lately?
maybe delete it from HACS and redownload?

as you can see I use the HACS resource too, and have no issue there. Any other issues with HACS?

I'll close this, as it is not an icon_color issue at all, if anything custom-ui, it is a HACS resource matter.

Ill have  a check a HACS, please do so too, and maybe meet at HACS discord to see what gives.
thanks for your investigations, appreciated.
cheers

**Closed by Mariusthvdb** 2023-01-10 14:40 UTC

**Comment by ildar170975** [comment] 2023-01-10 14:41
Note that this issue was created not by me - it was created by another person.
And you closed this issue.

**Comment by ildar170975** [comment] 2023-01-10 14:44
This behaviour is inappropriate.

**Comment by Mariusthvdb** [comment] 2023-01-10 14:48
Ok, so Ill give you the chance to delete that post, since it must be a mistake.
I'll check back later, so I can moderate this repo if necessary.

Meanwhile, let me suggest once more to fix your issue, before anything else.

**Comment by ildar170975** [comment] 2023-01-10 14:51
do what you wish )


> once more to fix your issue

and where is your suggestion?) Fix what exactly?

**Comment by Mariusthvdb** [comment] 2023-01-10 15:10
never deleted anything, I closed. No accusing going on. 
Since you wont help yourself, I can not either. 

Please calm down.

**Comment by ildar170975** [comment] 2023-01-10 15:14
Nonsense, there is nothing you suggested here to "help yourself" ))
The only thing you said "could be a HACS issue" - and closed this issue.

**Comment by kristianolofsson** [comment] 2023-01-10 15:23
Lets focus,

I reloaded the HACS plugin but its still not working.
<img width="1021" alt="Screenshot 2023-01-10 at 16 20 25" src="https://user-images.githubusercontent.com/7191232/211591036-0275b1e9-ef9c-47b1-96b3-bc1b58a52921.png">

All icons with the same customising file worked in 2022.x version.

The other icons are coloured using the card-mod for test. It works.

**Comment by Mariusthvdb** [comment] 2023-01-10 15:27
> I reloaded the HACS plugin but its still not working. 

Same question as above: Can you confirm it is loaded in inspector?

> The other icons are coloured using the card-mod for test. It works.

That is of no consequence for this issue, since it has a completely different technique of colorizing and does not set the attribute.

**Comment by kristianolofsson** [comment] 2023-01-10 15:37
Can you please detail out what you want me to check? The plugin states as loaded in HACS. Where do I find inspector? Im running a docker install

**Comment by Mariusthvdb** [comment] 2023-01-10 15:40
right click in most browsers to open the inspector, and select Console. all currently loaded custom resources are listed, see the screenshots of the 2 versions I posted in https://github.com/Mariusthvdb/custom-ui/issues/86#issuecomment-1377303809

**Comment by kristianolofsson** [comment] 2023-01-10 16:04
Failed to load resource: the server responded with a status of 404 (Not Found)

Deleted the plugin and reinstall, did not help.

http://x.x.x.x:8123/hacsfiles/custom-ui/custom-ui.js?hacstag=26755814820230106 net::ERR_ABORTED 404 (Not Found)
